name: 👀 Tests

permissions:
  id-token: write
  contents: read

env:
  DENO_JOBS: 8

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci:
    name: 🚑 Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Install Deno
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54 # v1.1.1

      - name: Run CI
        run: deno task ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DENO_NO_PACKAGE_JSON: 1
